// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package healthcheck

import (
	context "context"
	restspec "food-order-api/internal/delivery/rest/restspec"

	mock "github.com/stretchr/testify/mock"
)

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx
func (_m *MockUsecase) Check(ctx context.Context) restspec.HealthCheckResponse {
	ret := _m.Called(ctx)

	var r0 restspec.HealthCheckResponse
	if rf, ok := ret.Get(0).(func(context.Context) restspec.HealthCheckResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(restspec.HealthCheckResponse)
	}

	return r0
}
