// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package menus

import (
	context "context"
	model "food-order-api/internal/model"

	mock "github.com/stretchr/testify/mock"

	spec "food-order-api/internal/domain/menus/spec"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateAdditional provides a mock function with given fields: ctx, name, price
func (_m *MockRepository) CreateAdditional(ctx context.Context, name string, price int64) error {
	ret := _m.Called(ctx, name, price)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, name, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCategory provides a mock function with given fields: ctx, name
func (_m *MockRepository) CreateMenuCategory(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateEligibleAdditionalMenu provides a mock function with given fields: ctx, menuID, additionalID
func (_m *MockRepository) CreateEligibleAdditionalMenu(ctx context.Context, menuID int, additionalID int) error {
	ret := _m.Called(ctx, menuID, additionalID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, menuID, additionalID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMenu provides a mock function with given fields: ctx, arg
func (_m *MockRepository) CreateMenu(ctx context.Context, arg spec.CreateMenu) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.CreateMenu) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAdditional provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteAdditional(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCategory provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteMenuCategory(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteEligibleAdditionalMenu provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteEligibleAdditionalMenu(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMenu provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteMenu(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAdditionals provides a mock function with given fields: ctx
func (_m *MockRepository) FetchAdditionals(ctx context.Context) ([]model.Additionals, error) {
	ret := _m.Called(ctx)

	var r0 []model.Additionals
	if rf, ok := ret.Get(0).(func(context.Context) []model.Additionals); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Additionals)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchCategory provides a mock function with given fields: ctx
func (_m *MockRepository) FetchMenuCategory(ctx context.Context) ([]model.MenuCategories, error) {
	ret := _m.Called(ctx)

	var r0 []model.MenuCategories
	if rf, ok := ret.Get(0).(func(context.Context) []model.MenuCategories); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MenuCategories)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchEligibleAdditionalMenu provides a mock function with given fields: ctx
func (_m *MockRepository) FetchEligibleAdditionalMenu(ctx context.Context) ([]model.EligibleAdditionalMenu, error) {
	ret := _m.Called(ctx)

	var r0 []model.EligibleAdditionalMenu
	if rf, ok := ret.Get(0).(func(context.Context) []model.EligibleAdditionalMenu); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.EligibleAdditionalMenu)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchMenus provides a mock function with given fields: ctx
func (_m *MockRepository) FetchMenus(ctx context.Context) ([]model.Menus, error) {
	ret := _m.Called(ctx)

	var r0 []model.Menus
	if rf, ok := ret.Get(0).(func(context.Context) []model.Menus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Menus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAdditional provides a mock function with given fields: ctx, name, price, id
func (_m *MockRepository) UpdateAdditional(ctx context.Context, name string, price int64, id int) error {
	ret := _m.Called(ctx, name, price, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) error); ok {
		r0 = rf(ctx, name, price, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCategory provides a mock function with given fields: ctx, name, id
func (_m *MockRepository) UpdateMenuCategory(ctx context.Context, name string, id int) error {
	ret := _m.Called(ctx, name, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, name, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEligibleAdditionalMenu provides a mock function with given fields: ctx, menuID, additionalID, id
func (_m *MockRepository) UpdateEligibleAdditionalMenu(ctx context.Context, menuID int, additionalID int, id int) error {
	ret := _m.Called(ctx, menuID, additionalID, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, menuID, additionalID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMenu provides a mock function with given fields: ctx, arg
func (_m *MockRepository) UpdateMenu(ctx context.Context, arg spec.UpdateMenu) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.UpdateMenu) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
