// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package menus

import (
	context "context"
	restspec "food-order-api/internal/delivery/rest/restspec"

	mock "github.com/stretchr/testify/mock"

	spec "food-order-api/internal/domain/menus/spec"
)

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

// CreateAdditional provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) CreateAdditional(ctx context.Context, arg spec.CreateAdditionals) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.CreateAdditionals) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMenuCategory provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) CreateMenuCategory(ctx context.Context, arg spec.CreateMenuCategory) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.CreateMenuCategory) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateEligibleAdditionalMenu provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) CreateEligibleAdditionalMenu(ctx context.Context, arg spec.CreateEligibleAdditionalMenu) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.CreateEligibleAdditionalMenu) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMenu provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) CreateMenu(ctx context.Context, arg spec.CreateMenu) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.CreateMenu) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAdditional provides a mock function with given fields: ctx, id
func (_m *MockUsecase) DeleteAdditional(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMenuCategory provides a mock function with given fields: ctx, id
func (_m *MockUsecase) DeleteMenuCategory(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteEligibleAdditionalMenu provides a mock function with given fields: ctx, id
func (_m *MockUsecase) DeleteEligibleAdditionalMenu(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMenu provides a mock function with given fields: ctx, id
func (_m *MockUsecase) DeleteMenu(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchAdditionals provides a mock function with given fields: ctx
func (_m *MockUsecase) FetchAdditionals(ctx context.Context) ([]restspec.FetchAdditionalsResponse, error) {
	ret := _m.Called(ctx)

	var r0 []restspec.FetchAdditionalsResponse
	if rf, ok := ret.Get(0).(func(context.Context) []restspec.FetchAdditionalsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]restspec.FetchAdditionalsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchCategories provides a mock function with given fields: ctx
func (_m *MockUsecase) FetchCategories(ctx context.Context) ([]restspec.FetchMenuCategoriesResponse, error) {
	ret := _m.Called(ctx)

	var r0 []restspec.FetchMenuCategoriesResponse
	if rf, ok := ret.Get(0).(func(context.Context) []restspec.FetchMenuCategoriesResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]restspec.FetchMenuCategoriesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchEligibleAdditionalMenu provides a mock function with given fields: ctx
func (_m *MockUsecase) FetchEligibleAdditionalMenu(ctx context.Context) ([]restspec.FetchEligibleAdditionalMenuResponse, error) {
	ret := _m.Called(ctx)

	var r0 []restspec.FetchEligibleAdditionalMenuResponse
	if rf, ok := ret.Get(0).(func(context.Context) []restspec.FetchEligibleAdditionalMenuResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]restspec.FetchEligibleAdditionalMenuResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchMenus provides a mock function with given fields: ctx
func (_m *MockUsecase) FetchMenus(ctx context.Context) ([]restspec.FetchMenusResponse, error) {
	ret := _m.Called(ctx)

	var r0 []restspec.FetchMenusResponse
	if rf, ok := ret.Get(0).(func(context.Context) []restspec.FetchMenusResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]restspec.FetchMenusResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAdditional provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) UpdateAdditional(ctx context.Context, arg spec.UpdateAdditionals) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.UpdateAdditionals) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMenuCategory provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) UpdateMenuCategory(ctx context.Context, arg spec.UpdateMenuCategories) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.UpdateMenuCategories) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEligibleAdditionalMenu provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) UpdateEligibleAdditionalMenu(ctx context.Context, arg spec.UpdateEligibleAdditionalMenu) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.UpdateEligibleAdditionalMenu) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMenu provides a mock function with given fields: ctx, arg
func (_m *MockUsecase) UpdateMenu(ctx context.Context, arg spec.UpdateMenu) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, spec.UpdateMenu) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
