// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package orders

import (
	context "context"
	model "food-order-api/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// FetchAllOrders provides a mock function with given fields: ctx, userID
func (_m *MockRepository) FetchAllOrders(ctx context.Context, userID int) ([]model.Orders, error) {
	ret := _m.Called(ctx, userID)

	var r0 []model.Orders
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.Orders); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Orders)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchItemDetails provides a mock function with given fields: ctx, orderDetailID
func (_m *MockRepository) FetchItemDetails(ctx context.Context, orderDetailID int) ([]model.ItemDetails, error) {
	ret := _m.Called(ctx, orderDetailID)

	var r0 []model.ItemDetails
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.ItemDetails); ok {
		r0 = rf(ctx, orderDetailID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ItemDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, orderDetailID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchOrderDetails provides a mock function with given fields: ctx, orderID
func (_m *MockRepository) FetchOrderDetails(ctx context.Context, orderID int) ([]model.OrderDetails, error) {
	ret := _m.Called(ctx, orderID)

	var r0 []model.OrderDetails
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.OrderDetails); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OrderDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
